### ISSUE TITLE
리뷰하기 화면에 네모가 있어요

### ISSUE THREAD

**Issue by ChoiWonBeen** [BCSDLab/TEMP_PROJECT_FE#137]
<img width="1170" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/ae19bea5-565b-4b59-ba26-74c44c4b4776">

제곧내 

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
백엔드쪽 이슈로 리뷰하기쪽 작업 지금 안됨
