### ISSUE TITLE
리뷰 작성을 완료하고나서 마이페이지 -> 내가 쓴 글 데이터 초기화가 안돼요

### ISSUE THREAD

**Issue by ChoiWonBeen** [BCSDLab/TEMP_PROJECT_FE#138]
쿼리키 INVALIDATE 요망 
## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
@ChoiWonBeen 쿼리키 invalidate 한다는게 무슨말이야??

**Comment by hanagertrudeKim** [comment]
일단 구글key 관련해서 들어가는거는 다 지금 400에러나서.. 이거 한번 상의해봐야할것같아

**Comment by ChoiWonBeen** [comment]
마이페이지 내가쓴글 요청 (useQuery)
-> 쿼리키로 데이터 캐싱
글 쓰기
마이페이지 접근
-> 이때 캐싱된 데이터 반환


글쓰기에 캐시를 지우게끔 invalidateQuery동작이 필요하다는뜻이야 @hanagertrudekim
