### ISSUE TITLE
검색을 클릭하고 사이드바에 나오는 input 클릭하면 새로운 검색창나옴.

### ISSUE THREAD

**Issue by D0Dam** [BCSDLab/TEMP_PROJECT_FE#140]
## Describe the bug
제곧내. 자세한건 영상 참조.

## Expected behavior
그 input 에서 검색이 되어야함.

## Screenshot

https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/94999e57-1ce7-40f0-8824-ebc8bb49ae8b

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
스웨거 살펴보니까 놀랍게도 그게 의도된것같음
<img width="762" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/1cf66d41-e70a-406b-b2c2-c98f8cdb57d1">

**Comment by D0Dam** [comment]
....? w..o..w.....
