### ISSUE TITLE
기본 페이지를 가면 검색이 눌려져서 나옴

### ISSUE THREAD

**Issue by D0Dam** [BCSDLab/TEMP_PROJECT_FE#141]
## Describe the bug
제곧내, 사진 참조

## Expected behavior
검색이 안눌린상태로 기본 페이지 들어가기.

만약 이게 옳은 플로우라고 하면, 기본페이지를 갔을 때와 검색을 눌렀을 때의 차이가 필요함.

## Screenshot
<img width="617" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/0f77df52-68bd-4171-9dab-bf931b5ff87f">

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
스웨거상으론 기본값으로 그 검색창이 나오는듯. 그 다음에 기본 페이지 들어가면 들어갈수있게 하면 되려나??
<img width="909" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/3fdaafa8-d9e6-41fd-98f6-4b6fe33a015d">
