### ISSUE TITLE
에러 상태에서 로딩 상태를 보여줌

### ISSUE THREAD

**Issue by D0Dam** [BCSDLab/TEMP_PROJECT_FE#142]
## Describe the bug
제곧내, 자세한 내용은 사진 참조.

## Expected behavior
에러인 경우의 ui 필요

## Screenshot
<img width="1516" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/08779d9f-f452-41a1-8c10-e86f8caf3d78">

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
@D0Dam 
원래는 not found로 잘 가지는데, 저거 할당량 초과 이슈로 난것같아 
에러 페이지 양식이 없는것같은데 그냥 에러났을때도  not found로 보내지게 하면 되나?
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/adf7d914-f246-40cb-bd96-7c732150865e)

**Comment by D0Dam** [comment]
@hanagertrudekim  
> 에러 페이지 양식이 없는것같은데 그냥 에러났을때도  not found로 보내지게 하면 되나?
> 

그러면 댈 듯!
