### ISSUE TITLE
적절하지 않은 태그명

### ISSUE THREAD

**Issue by D0Dam** [BCSDLab/TEMP_PROJECT_FE#144]
## Describe the bug
제곧내, 검색 input 밑의 태그에서 관련없는 태그는 삭제 필요.
최소한 그냥 # 은 없애는 것이 좋아보임.

## Expected behavior
적절한 음식점 명이 들어가야함

## Screenshot
<img width="877" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/7b68f463-36ff-4303-85ef-750e22046e87">

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
trending은 백엔드에서 임시값으로 넣어둔것같음. 근데 #만 있는건 안뜨도록 조정할게요
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/b05aa263-7cef-4826-a02f-335f72f4789f)
