### ISSUE TITLE
태그 클릭 안됨

### ISSUE THREAD

**Issue by D0Dam** [BCSDLab/TEMP_PROJECT_FE#146]
## Describe the bug
제곧내

## Expected behavior
클릭을 하면 해당 태그명으로 검색이 되어야함.

클릭 이벤트를 삭제한다고 하면 hover css와 cursor:pointer 제거가 필요함

## Screenshot
<img width="974" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/4dea16ab-e88e-4e13-90f5-9fb83e733ac0">

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
일단 피그마에 질문 달아놓음

**Comment by hanagertrudeKim** [comment]
클릭 이벤트 삭제함 + 커서 포인터 없앰
