### ISSUE TITLE
NotFoundPage가 안뜸

### ISSUE THREAD

**Issue by D0Dam** [BCSDLab/TEMP_PROJECT_FE#148]
## Describe the bug
아래 사진과 같은 상황에서 안뜹니다.

## Screenshot
<img width="1689" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/c4c06098-2582-43ee-9879-4fee4f37497f">

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
404 ui 디자인 일단 없어서 404글씨만잇는 페이지로 대체하게함
