### ISSUE TITLE
팔로워 부분 오류

### ISSUE THREAD

**Issue by hyejun0228** [BCSDLab/TEMP_PROJECT_FE#151]
## Describe the bug
1. 팔로워 검색 안되고 있습니다..! 
2. 팔로워 검색시에 커서..?부분이 이상하게 깜빡거립니다. 모양이 이상하달까....작대기가 아니라 약간 작대기가 휘어졌달까...
<img width="361" alt="스크린샷 2024-01-09 오후 10 41 50" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/f6063f3e-10f8-4918-b818-441ae3b39684">

## To Reproduce
3. Click on '....'
4. Scroll down to '....'
5. See error

## Environment

**Desktop:**

**Smartphone:**

**Comment by chaeseungyun** [comment]
@hyejun0228 
현재 서버에서 500 에러를 주고 있는데 할당량 제한이 풀리고 다시 확인해보겠습니다
