### ISSUE TITLE
음식점 검색 결과쪽, 상세 페이지 403 error

### ISSUE THREAD

**Issue by hanagertrudeKim** [BCSDLab/TEMP_PROJECT_FE#163]
## Describe the bug
제곧내

## Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/4eb45f47-2190-4485-89c8-100da4ba6742)

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
이거 저번에 키 유출때문에 좀 꼬인것같은데, 스웨거에서 요청 보내봐도 403응답만 옴...
백엔드는 일단 변경없고 유지하자는데 조치가 필요할듯합니다 @D0Dam

**Comment by kimeodml** [comment]
@D0Dam @hanagertrudekim 구글 placeId 값을 넣어야 하는데 일반 string값으로 넣어서 에러 나는 것 같아요 제가 이어서 수정해 볼게요
