### ISSUE TITLE
리뷰 글쓰기 쪽에 일반 이미지 조차 제한때문에 업로드가 안됨

### ISSUE THREAD

**Issue by hanagertrudeKim** [BCSDLab/TEMP_PROJECT_FE#164]
## Describe the bug
이미지 업로드 성공한 케이스 있으면 댓글달아주세용

## Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/a2797a3f-4793-4f37-bf97-102957589638)

## Environment

**Desktop:**

**Smartphone:**

**Comment by LUNA-KK** [comment]
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/de477ed4-01e5-407c-8d9c-11a79b932c46)
크기 작은 사진은 들어가네요
