### ISSUE TITLE
daepan님의 애로사항

### ISSUE THREAD

**Issue by daepan** [BCSDLab/TEMP_PROJECT_FE#21]
가장 최근 PR에 적으려다가 이슈가 맞을 것 같아 이곳에 저의 애로사항을 적어봅니다.

1. github에서 recently activity에 Feature/#~~ 이라고 제목으로 쓰면 알아보기가 힘듭니다. 아마 기본적으로 저렇게 나오는 것 같은데 조금 귀찮겠지만 바꿔주면 어떤 기능인지 직관적으로 써주면 좋겠습니다.(이슈 제목을 긁어오는 깃헙 템플릿을 수정하면 베스트)

2. 로그인이랑 회원가입하면서 UI만 보고 느꼈는데 제가 맥북 13인치를 써서 그런지 상하단 스크롤바가 생기더군요.
저도 해당 UI는 기획이니깐 하고 넘길까 했지만, 17인치 width와 height을 기준으로 미디어쿼리를 사용해 margin값을 조절하거나 calc()를 이용했었습니다.
그때는 잘 모르던 때라 코드도 더럽고 난잡했지만 사용자와 의사소통하는 프론트엔드 입장에서 해당 UI 조절은 의미를 갖고 있다고 생각합니다.
이거는 다시 한번 해결해보고 싶은 문제군요ㅎ

3. 커밋은 누구는 영어로 누구는 한글로 하는데 통일하는 건 어떨까요?

위에 적힌 것은 단순한 애로사항이며, 여러분들이 고민해보면 좋을 것 같아 적어봅니다.

**Comment by ChoiWonBeen** [comment]
@jaewoogwak @hanagertrudekim @D0Dam @chaeseungyun @kimeodml 

현재 올려둔 PR 제목을 수정할 필요는 있어보입니다. 제 이전 closed된 PR을 참고해주세요.
`PULL_REQUEST_TEMPLATE`에서 title을 바꿀 수 있다면 이 또한 이슈템플릿처럼 수정해두겠습니다.

UI관련 내용은 이번에 `Auth` 개발에 관여한 분들이 이슈 생성해서 해결해주시는게 좋아보이네요.

커밋메시지는 [`commit-message-convention`](https://github.com/BCSDLab/JJBAKSA_FRONT_END/blob/develop/commit-message-convention.md)에 **한국어도 사용할 수 있다** 라고 명시해두긴 했는데, 한국어를 지향하는 방향이면 좋겠네요.

**Comment by SimYunSup** [comment]
저도 레귤러분들에게 당부해드릴 것들을 알립니다.
1. 다른 사람들의 PR도 체크해서 어떻게 개발해야하는지 확인하고, 물어볼 것이 있으면 PR에 코멘트를 달거나 채널에 질문하세요.
2. PR fullfillment는 장식이 아닙니다. 확인하고 체크해주세요. 체크 하는 방법을 모르겠다면 markdown 문법을 알아보세요.
3. commit 규칙은 장식이 아닙니다. 커밋 컨벤션 규칙을 지켜주시고 커밋 내용을 알 수 있도록 제목에 수정 내용을 적거나 커밋 body에 수정 내용을 적어주세요.
