### ISSUE TITLE
리뷰하기에서 리뷰하고 해당 상점 들어가면 내가 작성한 리뷰가 안뜸 

### ISSUE THREAD

**Issue by hanagertrudeKim** [BCSDLab/TEMP_PROJECT_FE#213]
## Screenshot
<img width="1184" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/92e0547c-c9d5-48d7-b39d-50342b6b8b2c">

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudeKim** [comment]
@kimeodml 요거 그때 리뷰 UI 작업 되었나요

<img width="500" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/842cdbea-aae9-4a1a-9866-9db752a37eff">

**Comment by kimeodml** [comment]
@hanagertrudekim `fetchMyReview`이 관련 api인데 추가적인 수정이 많이 필요할 것 같아요
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/c5944e06-784c-4436-a44d-fd5c5ca803d6)

**Comment by kimeodml** [comment]
새로고침해야지 뜸 수정 필요
