### ISSUE TITLE
로그인창 마진 이상해요

### ISSUE THREAD

**Issue by hanagertrudeKim** [BCSDLab/TEMP_PROJECT_FE#215]
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101982606/aa5b9286-8c68-4030-885f-d87434b4595a)

## Environment

**Desktop:**

**Smartphone:**

**Comment by kimeodml** [comment]
유일하게 로그인 페이지에만 TopNav가 있는데 이거 없애도 되지 않을까 싶어요
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/c700616d-2da8-4cc8-9204-0baf7bf3b4aa)
