### ISSUE TITLE
[Search] 롤링 배너 라이브러리 도입

### ISSUE THREAD

**Issue by jaewoogwak** [BCSDLab/TEMP_PROJECT_FE#37]
## 롤링 배너 라이브러리 도입
기존에는 요소를 여러 개 이어서 렌더링했는데요
```javascript
export default function RollingBanner({ trendings }: Props) {
  return (
    <div className={styles['search-banner']}>
      <strong>TRENDING</strong>
      <ul className={styles['search-banner__tag-list']}>
        <li className={styles['search-banner__tag']}>{trendings.map((tag) => `#${tag}`).join(' ')}</li>
        <li className={styles['search-banner__tag']}>{trendings.map((tag) => `#${tag}`).join(' ')}</li>
        <li className={styles['search-banner__tag']}>{trendings.map((tag) => `#${tag}`).join(' ')}</li>
      </ul>
    </div>
  );
}
```

이러면 `/trending` 호출해서 받아오는 `trending` 요소 개수가 바뀌면 일일이 대응해줘야 됩니다.

그래서 [롤링배너 비슷한 라이브러리](https://react-slick.neostack.com/docs/example/auto-play)를 리팩터링해서 적용해보는건 어떨까요?

`trending` 넘겨주기만하면 롤링 속도나 다양한 부분을 커스터마이징 할 수 있어서 유지보수할 때 좋을 거 같아요

## Design Screenshot

기존 검색 컴포넌트 롤링배너
![rollingbanner](https://user-images.githubusercontent.com/62415600/205441978-f78eebc1-ba3d-4ed8-9eb5-addef673b2d4.gif)

롤링배너 라이브러리 예시
![rollingLibrary](https://user-images.githubusercontent.com/62415600/205442183-6e8df25a-cbca-4809-868e-ac08b326f1ea.gif)

**Comment by ChoiWonBeen** [comment]
일일히 대응해야한다는게 무슨말인지 잘 이해를 못했습니다. `trending` 요청의 결과로 `li`태그를 렌더링하면 되는게 아닌건가요?

**Comment by jaewoogwak** [comment]
음 예를 들면 태그 갯수가 적을 때는 `li` 태그를 4~5개까지 렌더링해줘야 화면에서 끊김 없이 배너가 흐르는것처럼 보입니다
반대로 태그 갯수가 아주 많으면 `li` 태그를 2개 정도만 렌더링해줘도 됩니다.
무한 롤링 배너를 구현할때 `li` 태그를 여러개 사용해서 끊기지 않고 흐르도록 보이게 하더라구요
그래서 태그 갯수(ex: #마포 #맛집 등등)에 따라 렌더링해줘야하는 `li` 태그 갯수가 달라집니다.

**Comment by ChoiWonBeen** [comment]
`react-slick` 라이브러리가 동작하는 방식이, 한번에 보여질 내부 아이템의 개수를 정해서 전체 width와 나누어 각 아이템의 너비를 **일정하게** 정합니다.
ex) Swiper의 너비가 1000px, 보여질 아이템의 수가 5개일 때, 각각의 태그는 200px을 가지고 렌더링될겁니다.
지금 보이는 예시로는 태그 한개로 두던, 여러개를 모아두던 width가 고정값을 가지지 못하기 때문에 원하는 UI를 만들지 못할 것 같아요

물론 제가 모르는 다른 활용법이 있을 수 있으니 한번 설치해서 만들어보고 적합하다고 생각들면 사용해도 괜찮을 것 같아요.
그런데 우리가 scss를 직접적으로 사용하기로 했던게 번들 사이즈를 줄이기 위해서였기때문에, 일관성을 유지하려면 최대한 라이브러리의 도움 없이 만들어보는 게 좋을거라는 생각이 드네요.

**Comment by jaewoogwak** [comment]
아이템의 길이가 제각각일때를 생각하지 못했네요🥲 scss를 사용하는 이유에 대해서도 다시 리마인드 됐구요ㅋㅋㅋ scss만으로 최대한 만들어보겠습니다!
