### ISSUE TITLE
[Search] PC버전 검색 결과 추가

### ISSUE THREAD

**Issue by jaewoogwak** [BCSDLab/TEMP_PROJECT_FE#46]
## Feature/#17

PC버전 검색 결과를 추가할 예정입니다.
기존 모바일과 다르게 지도 아이콘이 없으며 검색 결과로 기본 6개의 아이템이 나타납니다.

해당 검색 결과 화면이 만들어진 후 PC버전 검색 상세 페이지는 다음 이슈에서 다루겠습니다.

## Progress

- [x] 검색 결과 리스트 보여주기
- [x] 아이템 선택하면 background 회색으로 hover
- [x] 영업 중/영업 종료 구분하기

## Design Screenshot
<img width="892" alt="image" src="https://user-images.githubusercontent.com/62415600/209975394-59473665-b11c-4a82-8996-037ab862dedb.png">

## Precautions

**Comment by ChoiWonBeen** [comment]
검색에는 페이지네이션이 적용되어서 API가 제공될 것 같은데, 6개씩 나온다고 해도 2페이지에 어떻게 접근할 수 있을지도 고려해야될 것 같아요.
결과가 6개보다 적은 경우도 생각해야할 것 같지만요 ㅋㅋ
